name: Deploy FE

on:
  push:
    branches:
      - main
    paths:
      - 'apps/fe/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd apps/fe
          docker build -t fe-app .
          docker stop fe-app || true
          docker rm fe-app || true
          docker run -d --name fe-app --restart always -p 127.0.0.1:8081:80 fe-app
